name: Docker Build & Publish

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clone code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Build Docker Image
        run: docker build -t arturoenqz/api:${{ github.sha }} .

      - name: Tag Latest
        run: docker tag arturoenqz/api:${{ github.sha }} arturoenqz/api:latest

      - name: Push Docker Image
        run: |
          docker push arturoenqz/api:${{ github.sha }}
          docker push arturoenqz/api:latest